
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-01
owner: ucsb-cs156-f24
repo_name: team01-f24-01
pull_requests: [{"author":{"id":"MDQ6VXNlcjczOTE2NDgw","is_bot":false,"login":"RealWeston34","name":"Scott Figueroa Weston"},"headRefName":"realweston34-RecommendationRequest-create-db","number":45,"title":"TEAM01-20 Create database table for RecommendationRequest","url":"https://github.com/ucsb-cs156-f24/team01-f24-01/pull/45"},{"author":{"id":"MDQ6VXNlcjYxNTcyODg3","is_bot":false,"login":"vzaveri23","name":"Viraj Zaveri"},"headRefName":"viraj-org-controller","number":44,"title":"Organization Controller and Unit Tests","url":"https://github.com/ucsb-cs156-f24/team01-f24-01/pull/44"},{"author":{"id":"MDQ6VXNlcjYxNTcyODg3","is_bot":false,"login":"vzaveri23","name":"Viraj Zaveri"},"headRefName":"viraj-ucsborg-create-db","number":43,"title":"Added organization database entity and defined schema","url":"https://github.com/ucsb-cs156-f24/team01-f24-01/pull/43"}]
