
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-01
owner: ucsb-cs156-f24
repo_name: team01-f24-01
pull_requests: [{"author":{"id":"MDQ6VXNlcjczOTE2NDgw","is_bot":false,"login":"RealWeston34","name":"Scott Figueroa Weston"},"headRefName":"realweston34-RecommendationRequest-single-record","number":52,"title":"TEAM01-22 Add GET endpoint for single record in RecommendationRequest","url":"https://github.com/ucsb-cs156-f24/team01-f24-01/pull/52"},{"author":{"id":"MDQ6VXNlcjYxNTcyODg3","is_bot":false,"login":"vzaveri23","name":"Viraj Zaveri"},"headRefName":"viraj-update-single-record","number":51,"title":"Added PUT request API endpoint","url":"https://github.com/ucsb-cs156-f24/team01-f24-01/pull/51"},{"author":{"id":"MDQ6VXNlcjYxNTcyODg3","is_bot":false,"login":"vzaveri23","name":"Viraj Zaveri"},"headRefName":"viraj-delete-single-record","number":49,"title":"Added DELETE API endpoint","url":"https://github.com/ucsb-cs156-f24/team01-f24-01/pull/49"},{"author":{"id":"MDQ6VXNlcjYxNTcyODg3","is_bot":false,"login":"vzaveri23","name":"Viraj Zaveri"},"headRefName":"viraj-org-controller","number":48,"title":"Changed function name to match database","url":"https://github.com/ucsb-cs156-f24/team01-f24-01/pull/48"}]
