
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-01
owner: ucsb-cs156-f24
repo_name: team01-f24-01
pull_requests: [{"author":{"id":"U_kgDOB8qFcQ","is_bot":false,"login":"cameronbyrne4","name":"Cameron Byrne"},"headRefName":"cameronbyrne4-HelpRequest-create-db","number":66,"title":"Created database table for Help Requests","url":"https://github.com/ucsb-cs156-f24/team01-f24-01/pull/66"}]
