
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-01
owner: ucsb-cs156-f24
repo_name: team01-f24-01
pull_requests: [{"author":{"id":"MDQ6VXNlcjYxMzk0NTgx","is_bot":false,"login":"Neamal","name":"Junhyung Yoon"},"headRefName":"junhyung-menuitemreview-create-db","number":62,"title":"Junhyung menuitemreview create db","url":"https://github.com/ucsb-cs156-f24/team01-f24-01/pull/62"},{"author":{"id":"U_kgDOB3DvtQ","is_bot":false,"login":"vincentc0202","name":""},"headRefName":"vincent-diningcommonsmenuitem-put-endpoint","number":59,"title":"TEAM01-11: UCSBDiningCommonsMenuItem put endpoint created","url":"https://github.com/ucsb-cs156-f24/team01-f24-01/pull/59"},{"author":{"id":"U_kgDOB3DvtQ","is_bot":false,"login":"vincentc0202","name":""},"headRefName":"vincent-diningcommonsmenuitem-get-endpoint","number":58,"title":"TEAM01-10: UCSBDiningCommonsMenuItem get endpoint created","url":"https://github.com/ucsb-cs156-f24/team01-f24-01/pull/58"},{"author":{"id":"U_kgDOB3DvtQ","is_bot":false,"login":"vincentc0202","name":""},"headRefName":"vincent-diningcommonsmenuitem-delete-endpoint","number":57,"title":"TEAM01-12 Create Delete Endpoint for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-f24/team01-f24-01/pull/57"},{"author":{"id":"U_kgDOB3DvtQ","is_bot":false,"login":"vincentc0202","name":""},"headRefName":"vincent-diningcommonsmenuitem-controllers","number":56,"title":"TEAM01-09, menuItem controllers added, along with get and post endpoints ","url":"https://github.com/ucsb-cs156-f24/team01-f24-01/pull/56"}]
