
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-01
owner: ucsb-cs156-f24
repo_name: team01-f24-01
pull_requests: [{"author":{"id":"U_kgDOB3DvtQ","is_bot":false,"login":"vincentc0202","name":""},"headRefName":"vincent-menuitem-controllers","number":55,"title":"TEAM01-09, menuItem controllers added, along with get and post endpoints","url":"https://github.com/ucsb-cs156-f24/team01-f24-01/pull/55"},{"author":{"id":"MDQ6VXNlcjczOTE2NDgw","is_bot":false,"login":"RealWeston34","name":"Scott Figueroa Weston"},"headRefName":"realweston34-RecommendationRequest-delete-endpoint","number":54,"title":"TEAM01-24 Add Delete Endpoint to Recommendation Request Table","url":"https://github.com/ucsb-cs156-f24/team01-f24-01/pull/54"},{"author":{"id":"MDQ6VXNlcjczOTE2NDgw","is_bot":false,"login":"RealWeston34","name":"Scott Figueroa Weston"},"headRefName":"realweston34-RecommendationRequest-edit-endpoint","number":53,"title":"TEAM01-23 Add PUT endpoint for Recommendation Request","url":"https://github.com/ucsb-cs156-f24/team01-f24-01/pull/53"},{"author":{"id":"MDQ6VXNlcjYxNTcyODg3","is_bot":false,"login":"vzaveri23","name":"Viraj Zaveri"},"headRefName":"viraj-update-single-record","number":51,"title":"Added PUT request API endpoint","url":"https://github.com/ucsb-cs156-f24/team01-f24-01/pull/51"},{"author":{"id":"MDQ6VXNlcjYxNTcyODg3","is_bot":false,"login":"vzaveri23","name":"Viraj Zaveri"},"headRefName":"viraj-delete-single-record","number":49,"title":"Added DELETE API endpoint","url":"https://github.com/ucsb-cs156-f24/team01-f24-01/pull/49"},{"author":{"id":"MDQ6VXNlcjYxNTcyODg3","is_bot":false,"login":"vzaveri23","name":"Viraj Zaveri"},"headRefName":"viraj-org-controller","number":48,"title":"Changed function name to match database","url":"https://github.com/ucsb-cs156-f24/team01-f24-01/pull/48"}]
